services:
  - type: web
    name: video-downloader-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RAPIDAPI_KEY
        value: 189810ce00mshba6d43848bf048fp11956ejsn61d09e6b2c7b
      - key: RAPIDAPI_HOST
        value: social-media-video-downloader.p.rapidapi.com
    autoDeploy: true