services:
  - type: web
    name: video-downloader-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install chromium --with-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    ports:
      - port: 10000
        protocol: http