services:
  - type: web
    name: video-downloader-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    ports:
      - port: 10000
        protocol: http